[package]
name = "http-server-actix"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
solana-client = "1.18.11"
solana-sdk = "1.18.11"
spl-token = "8.0.0"
base64 = "0.21" 
